### ISSUE TITLE
令牌错误

### ISSUE THREAD

**Issue by An-Jhon** [xudaolong/CodeVar#30]
ParseError: Unexpected token < in JSON at 
position 0 in "http://fanyi.youdao.com/
openapi.do": 
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="te...
    at /Users/ayd/Library/Application Support/
Alfred/Alfred.alfredpreferences/workflows/
user.workflow.B0E6D631-3BF4-43C2-A40D-
FB3B5C3AA82C/node_modules/got/index.js:118:14
    at processTicksAndRejections (node:internal/
process/task_queues:96:5)

**Comment by An-Jhon** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/44490800/182274964-7bd551c8-c7b0-4616-8cc5-102170253440.png">

**Comment by xudaolong** [comment]
@An-Jhon 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/9654838/182286090-3f6ddffb-ec8c-495c-af1c-07e831663f2e.png">

**Comment by peiqianggao** [comment]
@xudaolong MacOS Monterey 12.4，Node 17.3.0 使用报错了， 请问是版本问题吗？

[16:04:50.558] Logging Started...
[16:04:54.789] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Queuing argument 't'
[16:04:54.841] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Queuing argument 'te'
[16:04:55.036] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Queuing argument 'tes'
[16:04:55.107] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Queuing argument 'test'
[16:04:55.300] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Script with argv '(null)' finished
[16:04:55.301] ERROR: CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Code 1: {
	"items": [
		{
			"title": "ParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n```\n\n-\nCodeVar undefined\nAlfred 4.6.6\ndarwin x64 21.5.0",
				"largetype": "ParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[16:04:55.712] CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Script with argv '(null)' finished
[16:04:55.713] ERROR: CodeVar[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B%3E7058EC8E-E2B9-4134-A85D-C92BE50493FD)] Code 1: {
	"items": [
		{
			"title": "ParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n```\n\n-\nCodeVar undefined\nAlfred 4.6.6\ndarwin x64 21.5.0",
				"largetype": "ParseError: Unexpected token < in JSON at position 0 in \"http://fanyi.youdao.com/openapi.do\": \n<!DOCTYPE html>\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"te...\n    at /Users/gaopq/install/config/alfred/Alfred.alfredpreferences/workflows/user.workflow.08DE37A2-783E-4ACE-A8FC-2A9FA5CF939B/node_modules/got/index.js:118:14\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
